/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: esp_hosted_config.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "esp_hosted_config.pb-c.h"
void   cmd_get_status__init
                     (CmdGetStatus         *message)
{
  static CmdGetStatus init_value = CMD_GET_STATUS__INIT;
  *message = init_value;
}
size_t cmd_get_status__get_packed_size
                     (const CmdGetStatus *message)
{
  assert(message->base.descriptor == &cmd_get_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cmd_get_status__pack
                     (const CmdGetStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cmd_get_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cmd_get_status__pack_to_buffer
                     (const CmdGetStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cmd_get_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CmdGetStatus *
       cmd_get_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CmdGetStatus *)
     protobuf_c_message_unpack (&cmd_get_status__descriptor,
                                allocator, len, data);
}
void   cmd_get_status__free_unpacked
                     (CmdGetStatus *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cmd_get_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   resp_get_status__init
                     (RespGetStatus         *message)
{
  static RespGetStatus init_value = RESP_GET_STATUS__INIT;
  *message = init_value;
}
size_t resp_get_status__get_packed_size
                     (const RespGetStatus *message)
{
  assert(message->base.descriptor == &resp_get_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t resp_get_status__pack
                     (const RespGetStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &resp_get_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t resp_get_status__pack_to_buffer
                     (const RespGetStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &resp_get_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RespGetStatus *
       resp_get_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RespGetStatus *)
     protobuf_c_message_unpack (&resp_get_status__descriptor,
                                allocator, len, data);
}
void   resp_get_status__free_unpacked
                     (RespGetStatus *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &resp_get_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cmd_config__init
                     (CmdConfig         *message)
{
  static CmdConfig init_value = CMD_CONFIG__INIT;
  *message = init_value;
}
size_t cmd_config__get_packed_size
                     (const CmdConfig *message)
{
  assert(message->base.descriptor == &cmd_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cmd_config__pack
                     (const CmdConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cmd_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cmd_config__pack_to_buffer
                     (const CmdConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cmd_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CmdConfig *
       cmd_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CmdConfig *)
     protobuf_c_message_unpack (&cmd_config__descriptor,
                                allocator, len, data);
}
void   cmd_config__free_unpacked
                     (CmdConfig *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cmd_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   resp_config__init
                     (RespConfig         *message)
{
  static RespConfig init_value = RESP_CONFIG__INIT;
  *message = init_value;
}
size_t resp_config__get_packed_size
                     (const RespConfig *message)
{
  assert(message->base.descriptor == &resp_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t resp_config__pack
                     (const RespConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &resp_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t resp_config__pack_to_buffer
                     (const RespConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &resp_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RespConfig *
       resp_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RespConfig *)
     protobuf_c_message_unpack (&resp_config__descriptor,
                                allocator, len, data);
}
void   resp_config__free_unpacked
                     (RespConfig *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &resp_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   scan_result__init
                     (ScanResult         *message)
{
  static ScanResult init_value = SCAN_RESULT__INIT;
  *message = init_value;
}
size_t scan_result__get_packed_size
                     (const ScanResult *message)
{
  assert(message->base.descriptor == &scan_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scan_result__pack
                     (const ScanResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &scan_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scan_result__pack_to_buffer
                     (const ScanResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &scan_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ScanResult *
       scan_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ScanResult *)
     protobuf_c_message_unpack (&scan_result__descriptor,
                                allocator, len, data);
}
void   scan_result__free_unpacked
                     (ScanResult *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &scan_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cmd_scan_result__init
                     (CmdScanResult         *message)
{
  static CmdScanResult init_value = CMD_SCAN_RESULT__INIT;
  *message = init_value;
}
size_t cmd_scan_result__get_packed_size
                     (const CmdScanResult *message)
{
  assert(message->base.descriptor == &cmd_scan_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cmd_scan_result__pack
                     (const CmdScanResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cmd_scan_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cmd_scan_result__pack_to_buffer
                     (const CmdScanResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cmd_scan_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CmdScanResult *
       cmd_scan_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CmdScanResult *)
     protobuf_c_message_unpack (&cmd_scan_result__descriptor,
                                allocator, len, data);
}
void   cmd_scan_result__free_unpacked
                     (CmdScanResult *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cmd_scan_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   resp_scan_result__init
                     (RespScanResult         *message)
{
  static RespScanResult init_value = RESP_SCAN_RESULT__INIT;
  *message = init_value;
}
size_t resp_scan_result__get_packed_size
                     (const RespScanResult *message)
{
  assert(message->base.descriptor == &resp_scan_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t resp_scan_result__pack
                     (const RespScanResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &resp_scan_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t resp_scan_result__pack_to_buffer
                     (const RespScanResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &resp_scan_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RespScanResult *
       resp_scan_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RespScanResult *)
     protobuf_c_message_unpack (&resp_scan_result__descriptor,
                                allocator, len, data);
}
void   resp_scan_result__free_unpacked
                     (RespScanResult *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &resp_scan_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   connected_stalist__init
                     (ConnectedSTAList         *message)
{
  static ConnectedSTAList init_value = CONNECTED_STALIST__INIT;
  *message = init_value;
}
size_t connected_stalist__get_packed_size
                     (const ConnectedSTAList *message)
{
  assert(message->base.descriptor == &connected_stalist__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t connected_stalist__pack
                     (const ConnectedSTAList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &connected_stalist__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t connected_stalist__pack_to_buffer
                     (const ConnectedSTAList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &connected_stalist__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ConnectedSTAList *
       connected_stalist__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ConnectedSTAList *)
     protobuf_c_message_unpack (&connected_stalist__descriptor,
                                allocator, len, data);
}
void   connected_stalist__free_unpacked
                     (ConnectedSTAList *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &connected_stalist__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cmd_connected_sta__init
                     (CmdConnectedSTA         *message)
{
  static CmdConnectedSTA init_value = CMD_CONNECTED_STA__INIT;
  *message = init_value;
}
size_t cmd_connected_sta__get_packed_size
                     (const CmdConnectedSTA *message)
{
  assert(message->base.descriptor == &cmd_connected_sta__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cmd_connected_sta__pack
                     (const CmdConnectedSTA *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cmd_connected_sta__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cmd_connected_sta__pack_to_buffer
                     (const CmdConnectedSTA *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cmd_connected_sta__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CmdConnectedSTA *
       cmd_connected_sta__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CmdConnectedSTA *)
     protobuf_c_message_unpack (&cmd_connected_sta__descriptor,
                                allocator, len, data);
}
void   cmd_connected_sta__free_unpacked
                     (CmdConnectedSTA *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &cmd_connected_sta__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   resp_connected_sta__init
                     (RespConnectedSTA         *message)
{
  static RespConnectedSTA init_value = RESP_CONNECTED_STA__INIT;
  *message = init_value;
}
size_t resp_connected_sta__get_packed_size
                     (const RespConnectedSTA *message)
{
  assert(message->base.descriptor == &resp_connected_sta__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t resp_connected_sta__pack
                     (const RespConnectedSTA *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &resp_connected_sta__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t resp_connected_sta__pack_to_buffer
                     (const RespConnectedSTA *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &resp_connected_sta__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RespConnectedSTA *
       resp_connected_sta__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RespConnectedSTA *)
     protobuf_c_message_unpack (&resp_connected_sta__descriptor,
                                allocator, len, data);
}
void   resp_connected_sta__free_unpacked
                     (RespConnectedSTA *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &resp_connected_sta__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   esp_hosted_config_payload__init
                     (EspHostedConfigPayload         *message)
{
  static EspHostedConfigPayload init_value = ESP_HOSTED_CONFIG_PAYLOAD__INIT;
  *message = init_value;
}
size_t esp_hosted_config_payload__get_packed_size
                     (const EspHostedConfigPayload *message)
{
  assert(message->base.descriptor == &esp_hosted_config_payload__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t esp_hosted_config_payload__pack
                     (const EspHostedConfigPayload *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &esp_hosted_config_payload__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t esp_hosted_config_payload__pack_to_buffer
                     (const EspHostedConfigPayload *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &esp_hosted_config_payload__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EspHostedConfigPayload *
       esp_hosted_config_payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EspHostedConfigPayload *)
     protobuf_c_message_unpack (&esp_hosted_config_payload__descriptor,
                                allocator, len, data);
}
void   esp_hosted_config_payload__free_unpacked
                     (EspHostedConfigPayload *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &esp_hosted_config_payload__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor cmd_get_status__field_descriptors[2] =
{
  {
    "cmd",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CmdGetStatus, cmd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mode",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CmdGetStatus, has_mode),
    offsetof(CmdGetStatus, mode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmd_get_status__field_indices_by_name[] = {
  0,   /* field[0] = cmd */
  1,   /* field[1] = mode */
};
static const ProtobufCIntRange cmd_get_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cmd_get_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CmdGetStatus",
  "CmdGetStatus",
  "CmdGetStatus",
  "",
  sizeof(CmdGetStatus),
  2,
  cmd_get_status__field_descriptors,
  cmd_get_status__field_indices_by_name,
  1,  cmd_get_status__number_ranges,
  (ProtobufCMessageInit) cmd_get_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor resp_get_status__field_descriptors[2] =
{
  {
    "resp",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RespGetStatus, resp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mode",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(RespGetStatus, has_mode),
    offsetof(RespGetStatus, mode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned resp_get_status__field_indices_by_name[] = {
  1,   /* field[1] = mode */
  0,   /* field[0] = resp */
};
static const ProtobufCIntRange resp_get_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor resp_get_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RespGetStatus",
  "RespGetStatus",
  "RespGetStatus",
  "",
  sizeof(RespGetStatus),
  2,
  resp_get_status__field_descriptors,
  resp_get_status__field_indices_by_name,
  1,  resp_get_status__number_ranges,
  (ProtobufCMessageInit) resp_get_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cmd_config__field_descriptors[10] =
{
  {
    "ssid",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CmdConfig, ssid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pwd",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CmdConfig, pwd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ecn",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(CmdConfig, has_ecn),
    offsetof(CmdConfig, ecn),
    &encryption_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chnl",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CmdConfig, has_chnl),
    offsetof(CmdConfig, chnl),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_conn",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CmdConfig, has_max_conn),
    offsetof(CmdConfig, max_conn),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ssid_hidden",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(CmdConfig, has_ssid_hidden),
    offsetof(CmdConfig, ssid_hidden),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bssid",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CmdConfig, bssid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rssi",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CmdConfig, has_rssi),
    offsetof(CmdConfig, rssi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CmdConfig, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bw",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(CmdConfig, has_bw),
    offsetof(CmdConfig, bw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmd_config__field_indices_by_name[] = {
  6,   /* field[6] = bssid */
  9,   /* field[9] = bw */
  3,   /* field[3] = chnl */
  2,   /* field[2] = ecn */
  4,   /* field[4] = max_conn */
  1,   /* field[1] = pwd */
  7,   /* field[7] = rssi */
  0,   /* field[0] = ssid */
  5,   /* field[5] = ssid_hidden */
  8,   /* field[8] = status */
};
static const ProtobufCIntRange cmd_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor cmd_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CmdConfig",
  "CmdConfig",
  "CmdConfig",
  "",
  sizeof(CmdConfig),
  10,
  cmd_config__field_descriptors,
  cmd_config__field_indices_by_name,
  1,  cmd_config__number_ranges,
  (ProtobufCMessageInit) cmd_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor resp_config__field_descriptors[10] =
{
  {
    "ssid",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RespConfig, ssid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pwd",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RespConfig, pwd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ecn",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(RespConfig, has_ecn),
    offsetof(RespConfig, ecn),
    &encryption_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chnl",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(RespConfig, has_chnl),
    offsetof(RespConfig, chnl),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_conn",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(RespConfig, has_max_conn),
    offsetof(RespConfig, max_conn),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ssid_hidden",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(RespConfig, has_ssid_hidden),
    offsetof(RespConfig, ssid_hidden),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bssid",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RespConfig, bssid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rssi",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(RespConfig, has_rssi),
    offsetof(RespConfig, rssi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(RespConfig, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bw",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(RespConfig, has_bw),
    offsetof(RespConfig, bw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned resp_config__field_indices_by_name[] = {
  6,   /* field[6] = bssid */
  9,   /* field[9] = bw */
  3,   /* field[3] = chnl */
  2,   /* field[2] = ecn */
  4,   /* field[4] = max_conn */
  1,   /* field[1] = pwd */
  7,   /* field[7] = rssi */
  0,   /* field[0] = ssid */
  5,   /* field[5] = ssid_hidden */
  8,   /* field[8] = status */
};
static const ProtobufCIntRange resp_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor resp_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RespConfig",
  "RespConfig",
  "RespConfig",
  "",
  sizeof(RespConfig),
  10,
  resp_config__field_descriptors,
  resp_config__field_indices_by_name,
  1,  resp_config__number_ranges,
  (ProtobufCMessageInit) resp_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor scan_result__field_descriptors[5] =
{
  {
    "ssid",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ScanResult, has_ssid),
    offsetof(ScanResult, ssid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chnl",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ScanResult, has_chnl),
    offsetof(ScanResult, chnl),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rssi",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ScanResult, has_rssi),
    offsetof(ScanResult, rssi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bssid",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ScanResult, has_bssid),
    offsetof(ScanResult, bssid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ecn",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(ScanResult, has_ecn),
    offsetof(ScanResult, ecn),
    &encryption_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scan_result__field_indices_by_name[] = {
  3,   /* field[3] = bssid */
  1,   /* field[1] = chnl */
  4,   /* field[4] = ecn */
  2,   /* field[2] = rssi */
  0,   /* field[0] = ssid */
};
static const ProtobufCIntRange scan_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor scan_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ScanResult",
  "ScanResult",
  "ScanResult",
  "",
  sizeof(ScanResult),
  5,
  scan_result__field_descriptors,
  scan_result__field_indices_by_name,
  1,  scan_result__number_ranges,
  (ProtobufCMessageInit) scan_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define cmd_scan_result__field_descriptors NULL
#define cmd_scan_result__field_indices_by_name NULL
#define cmd_scan_result__number_ranges NULL
const ProtobufCMessageDescriptor cmd_scan_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CmdScanResult",
  "CmdScanResult",
  "CmdScanResult",
  "",
  sizeof(CmdScanResult),
  0,
  cmd_scan_result__field_descriptors,
  cmd_scan_result__field_indices_by_name,
  0,  cmd_scan_result__number_ranges,
  (ProtobufCMessageInit) cmd_scan_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor resp_scan_result__field_descriptors[2] =
{
  {
    "count",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RespScanResult, has_count),
    offsetof(RespScanResult, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "entries",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(RespScanResult, n_entries),
    offsetof(RespScanResult, entries),
    &scan_result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned resp_scan_result__field_indices_by_name[] = {
  0,   /* field[0] = count */
  1,   /* field[1] = entries */
};
static const ProtobufCIntRange resp_scan_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor resp_scan_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RespScanResult",
  "RespScanResult",
  "RespScanResult",
  "",
  sizeof(RespScanResult),
  2,
  resp_scan_result__field_descriptors,
  resp_scan_result__field_indices_by_name,
  1,  resp_scan_result__number_ranges,
  (ProtobufCMessageInit) resp_scan_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor connected_stalist__field_descriptors[2] =
{
  {
    "mac",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ConnectedSTAList, has_mac),
    offsetof(ConnectedSTAList, mac),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rssi",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ConnectedSTAList, has_rssi),
    offsetof(ConnectedSTAList, rssi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned connected_stalist__field_indices_by_name[] = {
  0,   /* field[0] = mac */
  1,   /* field[1] = rssi */
};
static const ProtobufCIntRange connected_stalist__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor connected_stalist__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ConnectedSTAList",
  "ConnectedSTAList",
  "ConnectedSTAList",
  "",
  sizeof(ConnectedSTAList),
  2,
  connected_stalist__field_descriptors,
  connected_stalist__field_indices_by_name,
  1,  connected_stalist__number_ranges,
  (ProtobufCMessageInit) connected_stalist__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define cmd_connected_sta__field_descriptors NULL
#define cmd_connected_sta__field_indices_by_name NULL
#define cmd_connected_sta__number_ranges NULL
const ProtobufCMessageDescriptor cmd_connected_sta__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CmdConnectedSTA",
  "CmdConnectedSTA",
  "CmdConnectedSTA",
  "",
  sizeof(CmdConnectedSTA),
  0,
  cmd_connected_sta__field_descriptors,
  cmd_connected_sta__field_indices_by_name,
  0,  cmd_connected_sta__number_ranges,
  (ProtobufCMessageInit) cmd_connected_sta__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor resp_connected_sta__field_descriptors[2] =
{
  {
    "num",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(RespConnectedSTA, has_num),
    offsetof(RespConnectedSTA, num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stations",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(RespConnectedSTA, n_stations),
    offsetof(RespConnectedSTA, stations),
    &connected_stalist__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned resp_connected_sta__field_indices_by_name[] = {
  0,   /* field[0] = num */
  1,   /* field[1] = stations */
};
static const ProtobufCIntRange resp_connected_sta__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor resp_connected_sta__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RespConnectedSTA",
  "RespConnectedSTA",
  "RespConnectedSTA",
  "",
  sizeof(RespConnectedSTA),
  2,
  resp_connected_sta__field_descriptors,
  resp_connected_sta__field_indices_by_name,
  1,  resp_connected_sta__number_ranges,
  (ProtobufCMessageInit) resp_connected_sta__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor esp_hosted_config_payload__field_descriptors[21] =
{
  {
    "msg",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(EspHostedConfigPayload, has_msg),
    offsetof(EspHostedConfigPayload, msg),
    &esp_hosted_config_msg_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd_get_mac_address",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, cmd_get_mac_address),
    &cmd_get_status__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resp_get_mac_address",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, resp_get_mac_address),
    &resp_get_status__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd_get_wifi_mode",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, cmd_get_wifi_mode),
    &cmd_get_status__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resp_get_wifi_mode",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, resp_get_wifi_mode),
    &resp_get_status__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd_set_wifi_mode",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, cmd_set_wifi_mode),
    &cmd_get_status__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resp_set_wifi_mode",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, resp_set_wifi_mode),
    &resp_get_status__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd_get_ap_config",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, cmd_get_ap_config),
    &cmd_config__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resp_get_ap_config",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, resp_get_ap_config),
    &resp_config__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd_set_ap_config",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, cmd_set_ap_config),
    &cmd_config__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resp_set_ap_config",
    19,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, resp_set_ap_config),
    &resp_config__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd_get_softap_config",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, cmd_get_softap_config),
    &cmd_config__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resp_get_softap_config",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, resp_get_softap_config),
    &resp_config__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd_set_softap_config",
    22,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, cmd_set_softap_config),
    &cmd_config__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resp_set_softap_config",
    23,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, resp_set_softap_config),
    &resp_config__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd_disconnect_ap",
    24,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, cmd_disconnect_ap),
    &cmd_get_status__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resp_disconnect_ap",
    25,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, resp_disconnect_ap),
    &resp_get_status__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd_scan_ap_list",
    26,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, cmd_scan_ap_list),
    &cmd_scan_result__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resp_scan_ap_list",
    27,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, resp_scan_ap_list),
    &resp_scan_result__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd_connected_stas_list",
    28,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, cmd_connected_stas_list),
    &cmd_connected_sta__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resp_connected_stas_list",
    29,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, resp_connected_stas_list),
    &resp_connected_sta__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned esp_hosted_config_payload__field_indices_by_name[] = {
  19,   /* field[19] = cmd_connected_stas_list */
  15,   /* field[15] = cmd_disconnect_ap */
  7,   /* field[7] = cmd_get_ap_config */
  1,   /* field[1] = cmd_get_mac_address */
  11,   /* field[11] = cmd_get_softap_config */
  3,   /* field[3] = cmd_get_wifi_mode */
  17,   /* field[17] = cmd_scan_ap_list */
  9,   /* field[9] = cmd_set_ap_config */
  13,   /* field[13] = cmd_set_softap_config */
  5,   /* field[5] = cmd_set_wifi_mode */
  0,   /* field[0] = msg */
  20,   /* field[20] = resp_connected_stas_list */
  16,   /* field[16] = resp_disconnect_ap */
  8,   /* field[8] = resp_get_ap_config */
  2,   /* field[2] = resp_get_mac_address */
  12,   /* field[12] = resp_get_softap_config */
  4,   /* field[4] = resp_get_wifi_mode */
  18,   /* field[18] = resp_scan_ap_list */
  10,   /* field[10] = resp_set_ap_config */
  14,   /* field[14] = resp_set_softap_config */
  6,   /* field[6] = resp_set_wifi_mode */
};
static const ProtobufCIntRange esp_hosted_config_payload__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 10, 1 },
  { 0, 21 }
};
const ProtobufCMessageDescriptor esp_hosted_config_payload__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EspHostedConfigPayload",
  "EspHostedConfigPayload",
  "EspHostedConfigPayload",
  "",
  sizeof(EspHostedConfigPayload),
  21,
  esp_hosted_config_payload__field_descriptors,
  esp_hosted_config_payload__field_indices_by_name,
  2,  esp_hosted_config_payload__number_ranges,
  (ProtobufCMessageInit) esp_hosted_config_payload__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue encryption_mode__enum_values_by_number[6] =
{
  { "Type_Open", "ENCRYPTION_MODE__Type_Open", 0 },
  { "Type_WEP", "ENCRYPTION_MODE__Type_WEP", 1 },
  { "Type_WPA_PSK", "ENCRYPTION_MODE__Type_WPA_PSK", 2 },
  { "Type_WPA2_PSK", "ENCRYPTION_MODE__Type_WPA2_PSK", 3 },
  { "Type_WPA_WPA2_PSK", "ENCRYPTION_MODE__Type_WPA_WPA2_PSK", 4 },
  { "Type_WPA2_ENTERPRISE", "ENCRYPTION_MODE__Type_WPA2_ENTERPRISE", 5 },
};
static const ProtobufCIntRange encryption_mode__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex encryption_mode__enum_values_by_name[6] =
{
  { "Type_Open", 0 },
  { "Type_WEP", 1 },
  { "Type_WPA2_ENTERPRISE", 5 },
  { "Type_WPA2_PSK", 3 },
  { "Type_WPA_PSK", 2 },
  { "Type_WPA_WPA2_PSK", 4 },
};
const ProtobufCEnumDescriptor encryption_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EncryptionMode",
  "EncryptionMode",
  "EncryptionMode",
  "",
  6,
  encryption_mode__enum_values_by_number,
  6,
  encryption_mode__enum_values_by_name,
  1,
  encryption_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue esp_hosted_config_msg_type__enum_values_by_number[20] =
{
  { "TypeCmdGetMACAddress", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeCmdGetMACAddress", 0 },
  { "TypeRespGetMACAddress", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeRespGetMACAddress", 1 },
  { "TypeCmdGetWiFiMode", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeCmdGetWiFiMode", 2 },
  { "TypeRespGetWiFiMode", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeRespGetWiFiMode", 3 },
  { "TypeCmdSetWiFiMode", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeCmdSetWiFiMode", 4 },
  { "TypeRespSetWiFiMode", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeRespSetWiFiMode", 5 },
  { "TypeCmdGetAPConfig", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeCmdGetAPConfig", 6 },
  { "TypeRespGetAPConfig", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeRespGetAPConfig", 7 },
  { "TypeCmdSetAPConfig", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeCmdSetAPConfig", 8 },
  { "TypeRespSetAPConfig", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeRespSetAPConfig", 9 },
  { "TypeCmdGetSoftAPConfig", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeCmdGetSoftAPConfig", 10 },
  { "TypeRespGetSoftAPConfig", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeRespGetSoftAPConfig", 11 },
  { "TypeCmdSetSoftAPConfig", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeCmdSetSoftAPConfig", 12 },
  { "TypeRespSetSoftAPConfig", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeRespSetSoftAPConfig", 13 },
  { "TypeCmdDisconnectAP", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeCmdDisconnectAP", 14 },
  { "TypeRespDisconnectAP", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeRespDisconnectAP", 15 },
  { "TypeCmdGetAPScanList", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeCmdGetAPScanList", 16 },
  { "TypeRespGetAPScanList", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeRespGetAPScanList", 17 },
  { "TypeCmdGetConnectedSTAList", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeCmdGetConnectedSTAList", 18 },
  { "TypeRespGetConnectedSTAList", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeRespGetConnectedSTAList", 19 },
};
static const ProtobufCIntRange esp_hosted_config_msg_type__value_ranges[] = {
{0, 0},{0, 20}
};
static const ProtobufCEnumValueIndex esp_hosted_config_msg_type__enum_values_by_name[20] =
{
  { "TypeCmdDisconnectAP", 14 },
  { "TypeCmdGetAPConfig", 6 },
  { "TypeCmdGetAPScanList", 16 },
  { "TypeCmdGetConnectedSTAList", 18 },
  { "TypeCmdGetMACAddress", 0 },
  { "TypeCmdGetSoftAPConfig", 10 },
  { "TypeCmdGetWiFiMode", 2 },
  { "TypeCmdSetAPConfig", 8 },
  { "TypeCmdSetSoftAPConfig", 12 },
  { "TypeCmdSetWiFiMode", 4 },
  { "TypeRespDisconnectAP", 15 },
  { "TypeRespGetAPConfig", 7 },
  { "TypeRespGetAPScanList", 17 },
  { "TypeRespGetConnectedSTAList", 19 },
  { "TypeRespGetMACAddress", 1 },
  { "TypeRespGetSoftAPConfig", 11 },
  { "TypeRespGetWiFiMode", 3 },
  { "TypeRespSetAPConfig", 9 },
  { "TypeRespSetSoftAPConfig", 13 },
  { "TypeRespSetWiFiMode", 5 },
};
const ProtobufCEnumDescriptor esp_hosted_config_msg_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EspHostedConfigMsgType",
  "EspHostedConfigMsgType",
  "EspHostedConfigMsgType",
  "",
  20,
  esp_hosted_config_msg_type__enum_values_by_number,
  20,
  esp_hosted_config_msg_type__enum_values_by_name,
  1,
  esp_hosted_config_msg_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
