/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: esp_hosted_config.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "esp_hosted_config.pb-c.h"
void   esp_hosted_cmd_get_status__init
                     (EspHostedCmdGetStatus         *message)
{
  static EspHostedCmdGetStatus init_value = ESP_HOSTED_CMD_GET_STATUS__INIT;
  *message = init_value;
}
size_t esp_hosted_cmd_get_status__get_packed_size
                     (const EspHostedCmdGetStatus *message)
{
  assert(message->base.descriptor == &esp_hosted_cmd_get_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t esp_hosted_cmd_get_status__pack
                     (const EspHostedCmdGetStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &esp_hosted_cmd_get_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t esp_hosted_cmd_get_status__pack_to_buffer
                     (const EspHostedCmdGetStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &esp_hosted_cmd_get_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EspHostedCmdGetStatus *
       esp_hosted_cmd_get_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EspHostedCmdGetStatus *)
     protobuf_c_message_unpack (&esp_hosted_cmd_get_status__descriptor,
                                allocator, len, data);
}
void   esp_hosted_cmd_get_status__free_unpacked
                     (EspHostedCmdGetStatus *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &esp_hosted_cmd_get_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   esp_hosted_resp_get_status__init
                     (EspHostedRespGetStatus         *message)
{
  static EspHostedRespGetStatus init_value = ESP_HOSTED_RESP_GET_STATUS__INIT;
  *message = init_value;
}
size_t esp_hosted_resp_get_status__get_packed_size
                     (const EspHostedRespGetStatus *message)
{
  assert(message->base.descriptor == &esp_hosted_resp_get_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t esp_hosted_resp_get_status__pack
                     (const EspHostedRespGetStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &esp_hosted_resp_get_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t esp_hosted_resp_get_status__pack_to_buffer
                     (const EspHostedRespGetStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &esp_hosted_resp_get_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EspHostedRespGetStatus *
       esp_hosted_resp_get_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EspHostedRespGetStatus *)
     protobuf_c_message_unpack (&esp_hosted_resp_get_status__descriptor,
                                allocator, len, data);
}
void   esp_hosted_resp_get_status__free_unpacked
                     (EspHostedRespGetStatus *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &esp_hosted_resp_get_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   esp_hosted_cmd_set_mac_address__init
                     (EspHostedCmdSetMacAddress         *message)
{
  static EspHostedCmdSetMacAddress init_value = ESP_HOSTED_CMD_SET_MAC_ADDRESS__INIT;
  *message = init_value;
}
size_t esp_hosted_cmd_set_mac_address__get_packed_size
                     (const EspHostedCmdSetMacAddress *message)
{
  assert(message->base.descriptor == &esp_hosted_cmd_set_mac_address__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t esp_hosted_cmd_set_mac_address__pack
                     (const EspHostedCmdSetMacAddress *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &esp_hosted_cmd_set_mac_address__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t esp_hosted_cmd_set_mac_address__pack_to_buffer
                     (const EspHostedCmdSetMacAddress *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &esp_hosted_cmd_set_mac_address__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EspHostedCmdSetMacAddress *
       esp_hosted_cmd_set_mac_address__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EspHostedCmdSetMacAddress *)
     protobuf_c_message_unpack (&esp_hosted_cmd_set_mac_address__descriptor,
                                allocator, len, data);
}
void   esp_hosted_cmd_set_mac_address__free_unpacked
                     (EspHostedCmdSetMacAddress *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &esp_hosted_cmd_set_mac_address__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   esp_hosted_resp_set_mac_address__init
                     (EspHostedRespSetMacAddress         *message)
{
  static EspHostedRespSetMacAddress init_value = ESP_HOSTED_RESP_SET_MAC_ADDRESS__INIT;
  *message = init_value;
}
size_t esp_hosted_resp_set_mac_address__get_packed_size
                     (const EspHostedRespSetMacAddress *message)
{
  assert(message->base.descriptor == &esp_hosted_resp_set_mac_address__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t esp_hosted_resp_set_mac_address__pack
                     (const EspHostedRespSetMacAddress *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &esp_hosted_resp_set_mac_address__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t esp_hosted_resp_set_mac_address__pack_to_buffer
                     (const EspHostedRespSetMacAddress *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &esp_hosted_resp_set_mac_address__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EspHostedRespSetMacAddress *
       esp_hosted_resp_set_mac_address__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EspHostedRespSetMacAddress *)
     protobuf_c_message_unpack (&esp_hosted_resp_set_mac_address__descriptor,
                                allocator, len, data);
}
void   esp_hosted_resp_set_mac_address__free_unpacked
                     (EspHostedRespSetMacAddress *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &esp_hosted_resp_set_mac_address__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   esp_hosted_cmd_config__init
                     (EspHostedCmdConfig         *message)
{
  static EspHostedCmdConfig init_value = ESP_HOSTED_CMD_CONFIG__INIT;
  *message = init_value;
}
size_t esp_hosted_cmd_config__get_packed_size
                     (const EspHostedCmdConfig *message)
{
  assert(message->base.descriptor == &esp_hosted_cmd_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t esp_hosted_cmd_config__pack
                     (const EspHostedCmdConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &esp_hosted_cmd_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t esp_hosted_cmd_config__pack_to_buffer
                     (const EspHostedCmdConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &esp_hosted_cmd_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EspHostedCmdConfig *
       esp_hosted_cmd_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EspHostedCmdConfig *)
     protobuf_c_message_unpack (&esp_hosted_cmd_config__descriptor,
                                allocator, len, data);
}
void   esp_hosted_cmd_config__free_unpacked
                     (EspHostedCmdConfig *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &esp_hosted_cmd_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   esp_hosted_resp_config__init
                     (EspHostedRespConfig         *message)
{
  static EspHostedRespConfig init_value = ESP_HOSTED_RESP_CONFIG__INIT;
  *message = init_value;
}
size_t esp_hosted_resp_config__get_packed_size
                     (const EspHostedRespConfig *message)
{
  assert(message->base.descriptor == &esp_hosted_resp_config__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t esp_hosted_resp_config__pack
                     (const EspHostedRespConfig *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &esp_hosted_resp_config__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t esp_hosted_resp_config__pack_to_buffer
                     (const EspHostedRespConfig *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &esp_hosted_resp_config__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EspHostedRespConfig *
       esp_hosted_resp_config__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EspHostedRespConfig *)
     protobuf_c_message_unpack (&esp_hosted_resp_config__descriptor,
                                allocator, len, data);
}
void   esp_hosted_resp_config__free_unpacked
                     (EspHostedRespConfig *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &esp_hosted_resp_config__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   esp_hosted_scan_result__init
                     (EspHostedScanResult         *message)
{
  static EspHostedScanResult init_value = ESP_HOSTED_SCAN_RESULT__INIT;
  *message = init_value;
}
size_t esp_hosted_scan_result__get_packed_size
                     (const EspHostedScanResult *message)
{
  assert(message->base.descriptor == &esp_hosted_scan_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t esp_hosted_scan_result__pack
                     (const EspHostedScanResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &esp_hosted_scan_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t esp_hosted_scan_result__pack_to_buffer
                     (const EspHostedScanResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &esp_hosted_scan_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EspHostedScanResult *
       esp_hosted_scan_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EspHostedScanResult *)
     protobuf_c_message_unpack (&esp_hosted_scan_result__descriptor,
                                allocator, len, data);
}
void   esp_hosted_scan_result__free_unpacked
                     (EspHostedScanResult *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &esp_hosted_scan_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   esp_hosted_cmd_scan_result__init
                     (EspHostedCmdScanResult         *message)
{
  static EspHostedCmdScanResult init_value = ESP_HOSTED_CMD_SCAN_RESULT__INIT;
  *message = init_value;
}
size_t esp_hosted_cmd_scan_result__get_packed_size
                     (const EspHostedCmdScanResult *message)
{
  assert(message->base.descriptor == &esp_hosted_cmd_scan_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t esp_hosted_cmd_scan_result__pack
                     (const EspHostedCmdScanResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &esp_hosted_cmd_scan_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t esp_hosted_cmd_scan_result__pack_to_buffer
                     (const EspHostedCmdScanResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &esp_hosted_cmd_scan_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EspHostedCmdScanResult *
       esp_hosted_cmd_scan_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EspHostedCmdScanResult *)
     protobuf_c_message_unpack (&esp_hosted_cmd_scan_result__descriptor,
                                allocator, len, data);
}
void   esp_hosted_cmd_scan_result__free_unpacked
                     (EspHostedCmdScanResult *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &esp_hosted_cmd_scan_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   esp_hosted_resp_scan_result__init
                     (EspHostedRespScanResult         *message)
{
  static EspHostedRespScanResult init_value = ESP_HOSTED_RESP_SCAN_RESULT__INIT;
  *message = init_value;
}
size_t esp_hosted_resp_scan_result__get_packed_size
                     (const EspHostedRespScanResult *message)
{
  assert(message->base.descriptor == &esp_hosted_resp_scan_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t esp_hosted_resp_scan_result__pack
                     (const EspHostedRespScanResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &esp_hosted_resp_scan_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t esp_hosted_resp_scan_result__pack_to_buffer
                     (const EspHostedRespScanResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &esp_hosted_resp_scan_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EspHostedRespScanResult *
       esp_hosted_resp_scan_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EspHostedRespScanResult *)
     protobuf_c_message_unpack (&esp_hosted_resp_scan_result__descriptor,
                                allocator, len, data);
}
void   esp_hosted_resp_scan_result__free_unpacked
                     (EspHostedRespScanResult *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &esp_hosted_resp_scan_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   esp_hosted_connected_stalist__init
                     (EspHostedConnectedSTAList         *message)
{
  static EspHostedConnectedSTAList init_value = ESP_HOSTED_CONNECTED_STALIST__INIT;
  *message = init_value;
}
size_t esp_hosted_connected_stalist__get_packed_size
                     (const EspHostedConnectedSTAList *message)
{
  assert(message->base.descriptor == &esp_hosted_connected_stalist__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t esp_hosted_connected_stalist__pack
                     (const EspHostedConnectedSTAList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &esp_hosted_connected_stalist__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t esp_hosted_connected_stalist__pack_to_buffer
                     (const EspHostedConnectedSTAList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &esp_hosted_connected_stalist__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EspHostedConnectedSTAList *
       esp_hosted_connected_stalist__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EspHostedConnectedSTAList *)
     protobuf_c_message_unpack (&esp_hosted_connected_stalist__descriptor,
                                allocator, len, data);
}
void   esp_hosted_connected_stalist__free_unpacked
                     (EspHostedConnectedSTAList *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &esp_hosted_connected_stalist__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   esp_hosted_cmd_connected_sta__init
                     (EspHostedCmdConnectedSTA         *message)
{
  static EspHostedCmdConnectedSTA init_value = ESP_HOSTED_CMD_CONNECTED_STA__INIT;
  *message = init_value;
}
size_t esp_hosted_cmd_connected_sta__get_packed_size
                     (const EspHostedCmdConnectedSTA *message)
{
  assert(message->base.descriptor == &esp_hosted_cmd_connected_sta__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t esp_hosted_cmd_connected_sta__pack
                     (const EspHostedCmdConnectedSTA *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &esp_hosted_cmd_connected_sta__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t esp_hosted_cmd_connected_sta__pack_to_buffer
                     (const EspHostedCmdConnectedSTA *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &esp_hosted_cmd_connected_sta__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EspHostedCmdConnectedSTA *
       esp_hosted_cmd_connected_sta__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EspHostedCmdConnectedSTA *)
     protobuf_c_message_unpack (&esp_hosted_cmd_connected_sta__descriptor,
                                allocator, len, data);
}
void   esp_hosted_cmd_connected_sta__free_unpacked
                     (EspHostedCmdConnectedSTA *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &esp_hosted_cmd_connected_sta__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   esp_hosted_resp_connected_sta__init
                     (EspHostedRespConnectedSTA         *message)
{
  static EspHostedRespConnectedSTA init_value = ESP_HOSTED_RESP_CONNECTED_STA__INIT;
  *message = init_value;
}
size_t esp_hosted_resp_connected_sta__get_packed_size
                     (const EspHostedRespConnectedSTA *message)
{
  assert(message->base.descriptor == &esp_hosted_resp_connected_sta__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t esp_hosted_resp_connected_sta__pack
                     (const EspHostedRespConnectedSTA *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &esp_hosted_resp_connected_sta__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t esp_hosted_resp_connected_sta__pack_to_buffer
                     (const EspHostedRespConnectedSTA *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &esp_hosted_resp_connected_sta__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EspHostedRespConnectedSTA *
       esp_hosted_resp_connected_sta__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EspHostedRespConnectedSTA *)
     protobuf_c_message_unpack (&esp_hosted_resp_connected_sta__descriptor,
                                allocator, len, data);
}
void   esp_hosted_resp_connected_sta__free_unpacked
                     (EspHostedRespConnectedSTA *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &esp_hosted_resp_connected_sta__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   esp_hosted_cmd_set_power_save_mode__init
                     (EspHostedCmdSetPowerSaveMode         *message)
{
  static EspHostedCmdSetPowerSaveMode init_value = ESP_HOSTED_CMD_SET_POWER_SAVE_MODE__INIT;
  *message = init_value;
}
size_t esp_hosted_cmd_set_power_save_mode__get_packed_size
                     (const EspHostedCmdSetPowerSaveMode *message)
{
  assert(message->base.descriptor == &esp_hosted_cmd_set_power_save_mode__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t esp_hosted_cmd_set_power_save_mode__pack
                     (const EspHostedCmdSetPowerSaveMode *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &esp_hosted_cmd_set_power_save_mode__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t esp_hosted_cmd_set_power_save_mode__pack_to_buffer
                     (const EspHostedCmdSetPowerSaveMode *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &esp_hosted_cmd_set_power_save_mode__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EspHostedCmdSetPowerSaveMode *
       esp_hosted_cmd_set_power_save_mode__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EspHostedCmdSetPowerSaveMode *)
     protobuf_c_message_unpack (&esp_hosted_cmd_set_power_save_mode__descriptor,
                                allocator, len, data);
}
void   esp_hosted_cmd_set_power_save_mode__free_unpacked
                     (EspHostedCmdSetPowerSaveMode *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &esp_hosted_cmd_set_power_save_mode__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   esp_hosted_resp_set_power_save_mode__init
                     (EspHostedRespSetPowerSaveMode         *message)
{
  static EspHostedRespSetPowerSaveMode init_value = ESP_HOSTED_RESP_SET_POWER_SAVE_MODE__INIT;
  *message = init_value;
}
size_t esp_hosted_resp_set_power_save_mode__get_packed_size
                     (const EspHostedRespSetPowerSaveMode *message)
{
  assert(message->base.descriptor == &esp_hosted_resp_set_power_save_mode__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t esp_hosted_resp_set_power_save_mode__pack
                     (const EspHostedRespSetPowerSaveMode *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &esp_hosted_resp_set_power_save_mode__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t esp_hosted_resp_set_power_save_mode__pack_to_buffer
                     (const EspHostedRespSetPowerSaveMode *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &esp_hosted_resp_set_power_save_mode__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EspHostedRespSetPowerSaveMode *
       esp_hosted_resp_set_power_save_mode__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EspHostedRespSetPowerSaveMode *)
     protobuf_c_message_unpack (&esp_hosted_resp_set_power_save_mode__descriptor,
                                allocator, len, data);
}
void   esp_hosted_resp_set_power_save_mode__free_unpacked
                     (EspHostedRespSetPowerSaveMode *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &esp_hosted_resp_set_power_save_mode__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   esp_hosted_cmd_get_power_save_mode__init
                     (EspHostedCmdGetPowerSaveMode         *message)
{
  static EspHostedCmdGetPowerSaveMode init_value = ESP_HOSTED_CMD_GET_POWER_SAVE_MODE__INIT;
  *message = init_value;
}
size_t esp_hosted_cmd_get_power_save_mode__get_packed_size
                     (const EspHostedCmdGetPowerSaveMode *message)
{
  assert(message->base.descriptor == &esp_hosted_cmd_get_power_save_mode__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t esp_hosted_cmd_get_power_save_mode__pack
                     (const EspHostedCmdGetPowerSaveMode *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &esp_hosted_cmd_get_power_save_mode__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t esp_hosted_cmd_get_power_save_mode__pack_to_buffer
                     (const EspHostedCmdGetPowerSaveMode *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &esp_hosted_cmd_get_power_save_mode__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EspHostedCmdGetPowerSaveMode *
       esp_hosted_cmd_get_power_save_mode__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EspHostedCmdGetPowerSaveMode *)
     protobuf_c_message_unpack (&esp_hosted_cmd_get_power_save_mode__descriptor,
                                allocator, len, data);
}
void   esp_hosted_cmd_get_power_save_mode__free_unpacked
                     (EspHostedCmdGetPowerSaveMode *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &esp_hosted_cmd_get_power_save_mode__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   esp_hosted_resp_get_power_save_mode__init
                     (EspHostedRespGetPowerSaveMode         *message)
{
  static EspHostedRespGetPowerSaveMode init_value = ESP_HOSTED_RESP_GET_POWER_SAVE_MODE__INIT;
  *message = init_value;
}
size_t esp_hosted_resp_get_power_save_mode__get_packed_size
                     (const EspHostedRespGetPowerSaveMode *message)
{
  assert(message->base.descriptor == &esp_hosted_resp_get_power_save_mode__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t esp_hosted_resp_get_power_save_mode__pack
                     (const EspHostedRespGetPowerSaveMode *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &esp_hosted_resp_get_power_save_mode__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t esp_hosted_resp_get_power_save_mode__pack_to_buffer
                     (const EspHostedRespGetPowerSaveMode *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &esp_hosted_resp_get_power_save_mode__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EspHostedRespGetPowerSaveMode *
       esp_hosted_resp_get_power_save_mode__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EspHostedRespGetPowerSaveMode *)
     protobuf_c_message_unpack (&esp_hosted_resp_get_power_save_mode__descriptor,
                                allocator, len, data);
}
void   esp_hosted_resp_get_power_save_mode__free_unpacked
                     (EspHostedRespGetPowerSaveMode *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &esp_hosted_resp_get_power_save_mode__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   esp_hosted_config_payload__init
                     (EspHostedConfigPayload         *message)
{
  static EspHostedConfigPayload init_value = ESP_HOSTED_CONFIG_PAYLOAD__INIT;
  *message = init_value;
}
size_t esp_hosted_config_payload__get_packed_size
                     (const EspHostedConfigPayload *message)
{
  assert(message->base.descriptor == &esp_hosted_config_payload__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t esp_hosted_config_payload__pack
                     (const EspHostedConfigPayload *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &esp_hosted_config_payload__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t esp_hosted_config_payload__pack_to_buffer
                     (const EspHostedConfigPayload *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &esp_hosted_config_payload__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EspHostedConfigPayload *
       esp_hosted_config_payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EspHostedConfigPayload *)
     protobuf_c_message_unpack (&esp_hosted_config_payload__descriptor,
                                allocator, len, data);
}
void   esp_hosted_config_payload__free_unpacked
                     (EspHostedConfigPayload *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &esp_hosted_config_payload__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor esp_hosted_cmd_get_status__field_descriptors[2] =
{
  {
    "cmd",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(EspHostedCmdGetStatus, cmd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mode",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(EspHostedCmdGetStatus, has_mode),
    offsetof(EspHostedCmdGetStatus, mode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned esp_hosted_cmd_get_status__field_indices_by_name[] = {
  0,   /* field[0] = cmd */
  1,   /* field[1] = mode */
};
static const ProtobufCIntRange esp_hosted_cmd_get_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor esp_hosted_cmd_get_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EspHostedCmdGetStatus",
  "EspHostedCmdGetStatus",
  "EspHostedCmdGetStatus",
  "",
  sizeof(EspHostedCmdGetStatus),
  2,
  esp_hosted_cmd_get_status__field_descriptors,
  esp_hosted_cmd_get_status__field_indices_by_name,
  1,  esp_hosted_cmd_get_status__number_ranges,
  (ProtobufCMessageInit) esp_hosted_cmd_get_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor esp_hosted_resp_get_status__field_descriptors[2] =
{
  {
    "resp",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(EspHostedRespGetStatus, resp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mode",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(EspHostedRespGetStatus, has_mode),
    offsetof(EspHostedRespGetStatus, mode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned esp_hosted_resp_get_status__field_indices_by_name[] = {
  1,   /* field[1] = mode */
  0,   /* field[0] = resp */
};
static const ProtobufCIntRange esp_hosted_resp_get_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor esp_hosted_resp_get_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EspHostedRespGetStatus",
  "EspHostedRespGetStatus",
  "EspHostedRespGetStatus",
  "",
  sizeof(EspHostedRespGetStatus),
  2,
  esp_hosted_resp_get_status__field_descriptors,
  esp_hosted_resp_get_status__field_indices_by_name,
  1,  esp_hosted_resp_get_status__number_ranges,
  (ProtobufCMessageInit) esp_hosted_resp_get_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor esp_hosted_cmd_set_mac_address__field_descriptors[2] =
{
  {
    "mac",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(EspHostedCmdSetMacAddress, has_mac),
    offsetof(EspHostedCmdSetMacAddress, mac),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mode",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(EspHostedCmdSetMacAddress, has_mode),
    offsetof(EspHostedCmdSetMacAddress, mode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned esp_hosted_cmd_set_mac_address__field_indices_by_name[] = {
  0,   /* field[0] = mac */
  1,   /* field[1] = mode */
};
static const ProtobufCIntRange esp_hosted_cmd_set_mac_address__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor esp_hosted_cmd_set_mac_address__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EspHostedCmdSetMacAddress",
  "EspHostedCmdSetMacAddress",
  "EspHostedCmdSetMacAddress",
  "",
  sizeof(EspHostedCmdSetMacAddress),
  2,
  esp_hosted_cmd_set_mac_address__field_descriptors,
  esp_hosted_cmd_set_mac_address__field_indices_by_name,
  1,  esp_hosted_cmd_set_mac_address__number_ranges,
  (ProtobufCMessageInit) esp_hosted_cmd_set_mac_address__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor esp_hosted_resp_set_mac_address__field_descriptors[1] =
{
  {
    "resp",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(EspHostedRespSetMacAddress, has_resp),
    offsetof(EspHostedRespSetMacAddress, resp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned esp_hosted_resp_set_mac_address__field_indices_by_name[] = {
  0,   /* field[0] = resp */
};
static const ProtobufCIntRange esp_hosted_resp_set_mac_address__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor esp_hosted_resp_set_mac_address__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EspHostedRespSetMacAddress",
  "EspHostedRespSetMacAddress",
  "EspHostedRespSetMacAddress",
  "",
  sizeof(EspHostedRespSetMacAddress),
  1,
  esp_hosted_resp_set_mac_address__field_descriptors,
  esp_hosted_resp_set_mac_address__field_indices_by_name,
  1,  esp_hosted_resp_set_mac_address__number_ranges,
  (ProtobufCMessageInit) esp_hosted_resp_set_mac_address__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor esp_hosted_cmd_config__field_descriptors[12] =
{
  {
    "ssid",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(EspHostedCmdConfig, ssid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pwd",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(EspHostedCmdConfig, pwd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ecn",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(EspHostedCmdConfig, has_ecn),
    offsetof(EspHostedCmdConfig, ecn),
    &esp_hosted_encryption_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chnl",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(EspHostedCmdConfig, has_chnl),
    offsetof(EspHostedCmdConfig, chnl),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_conn",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(EspHostedCmdConfig, has_max_conn),
    offsetof(EspHostedCmdConfig, max_conn),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ssid_hidden",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(EspHostedCmdConfig, has_ssid_hidden),
    offsetof(EspHostedCmdConfig, ssid_hidden),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bssid",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(EspHostedCmdConfig, bssid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rssi",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(EspHostedCmdConfig, has_rssi),
    offsetof(EspHostedCmdConfig, rssi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(EspHostedCmdConfig, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bw",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(EspHostedCmdConfig, has_bw),
    offsetof(EspHostedCmdConfig, bw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_wpa3_supported",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(EspHostedCmdConfig, has_is_wpa3_supported),
    offsetof(EspHostedCmdConfig, is_wpa3_supported),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "listen_interval",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(EspHostedCmdConfig, has_listen_interval),
    offsetof(EspHostedCmdConfig, listen_interval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned esp_hosted_cmd_config__field_indices_by_name[] = {
  6,   /* field[6] = bssid */
  9,   /* field[9] = bw */
  3,   /* field[3] = chnl */
  2,   /* field[2] = ecn */
  10,   /* field[10] = is_wpa3_supported */
  11,   /* field[11] = listen_interval */
  4,   /* field[4] = max_conn */
  1,   /* field[1] = pwd */
  7,   /* field[7] = rssi */
  0,   /* field[0] = ssid */
  5,   /* field[5] = ssid_hidden */
  8,   /* field[8] = status */
};
static const ProtobufCIntRange esp_hosted_cmd_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor esp_hosted_cmd_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EspHostedCmdConfig",
  "EspHostedCmdConfig",
  "EspHostedCmdConfig",
  "",
  sizeof(EspHostedCmdConfig),
  12,
  esp_hosted_cmd_config__field_descriptors,
  esp_hosted_cmd_config__field_indices_by_name,
  1,  esp_hosted_cmd_config__number_ranges,
  (ProtobufCMessageInit) esp_hosted_cmd_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor esp_hosted_resp_config__field_descriptors[12] =
{
  {
    "ssid",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(EspHostedRespConfig, ssid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pwd",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(EspHostedRespConfig, pwd),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ecn",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(EspHostedRespConfig, has_ecn),
    offsetof(EspHostedRespConfig, ecn),
    &esp_hosted_encryption_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chnl",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(EspHostedRespConfig, has_chnl),
    offsetof(EspHostedRespConfig, chnl),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_conn",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(EspHostedRespConfig, has_max_conn),
    offsetof(EspHostedRespConfig, max_conn),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ssid_hidden",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(EspHostedRespConfig, has_ssid_hidden),
    offsetof(EspHostedRespConfig, ssid_hidden),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bssid",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(EspHostedRespConfig, bssid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rssi",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(EspHostedRespConfig, has_rssi),
    offsetof(EspHostedRespConfig, rssi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(EspHostedRespConfig, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bw",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(EspHostedRespConfig, has_bw),
    offsetof(EspHostedRespConfig, bw),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_wpa3_supported",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(EspHostedRespConfig, has_is_wpa3_supported),
    offsetof(EspHostedRespConfig, is_wpa3_supported),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "listen_interval",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(EspHostedRespConfig, has_listen_interval),
    offsetof(EspHostedRespConfig, listen_interval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned esp_hosted_resp_config__field_indices_by_name[] = {
  6,   /* field[6] = bssid */
  9,   /* field[9] = bw */
  3,   /* field[3] = chnl */
  2,   /* field[2] = ecn */
  10,   /* field[10] = is_wpa3_supported */
  11,   /* field[11] = listen_interval */
  4,   /* field[4] = max_conn */
  1,   /* field[1] = pwd */
  7,   /* field[7] = rssi */
  0,   /* field[0] = ssid */
  5,   /* field[5] = ssid_hidden */
  8,   /* field[8] = status */
};
static const ProtobufCIntRange esp_hosted_resp_config__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor esp_hosted_resp_config__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EspHostedRespConfig",
  "EspHostedRespConfig",
  "EspHostedRespConfig",
  "",
  sizeof(EspHostedRespConfig),
  12,
  esp_hosted_resp_config__field_descriptors,
  esp_hosted_resp_config__field_indices_by_name,
  1,  esp_hosted_resp_config__number_ranges,
  (ProtobufCMessageInit) esp_hosted_resp_config__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor esp_hosted_scan_result__field_descriptors[5] =
{
  {
    "ssid",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(EspHostedScanResult, has_ssid),
    offsetof(EspHostedScanResult, ssid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chnl",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(EspHostedScanResult, has_chnl),
    offsetof(EspHostedScanResult, chnl),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rssi",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(EspHostedScanResult, has_rssi),
    offsetof(EspHostedScanResult, rssi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bssid",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(EspHostedScanResult, has_bssid),
    offsetof(EspHostedScanResult, bssid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ecn",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(EspHostedScanResult, has_ecn),
    offsetof(EspHostedScanResult, ecn),
    &esp_hosted_encryption_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned esp_hosted_scan_result__field_indices_by_name[] = {
  3,   /* field[3] = bssid */
  1,   /* field[1] = chnl */
  4,   /* field[4] = ecn */
  2,   /* field[2] = rssi */
  0,   /* field[0] = ssid */
};
static const ProtobufCIntRange esp_hosted_scan_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor esp_hosted_scan_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EspHostedScanResult",
  "EspHostedScanResult",
  "EspHostedScanResult",
  "",
  sizeof(EspHostedScanResult),
  5,
  esp_hosted_scan_result__field_descriptors,
  esp_hosted_scan_result__field_indices_by_name,
  1,  esp_hosted_scan_result__number_ranges,
  (ProtobufCMessageInit) esp_hosted_scan_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define esp_hosted_cmd_scan_result__field_descriptors NULL
#define esp_hosted_cmd_scan_result__field_indices_by_name NULL
#define esp_hosted_cmd_scan_result__number_ranges NULL
const ProtobufCMessageDescriptor esp_hosted_cmd_scan_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EspHostedCmdScanResult",
  "EspHostedCmdScanResult",
  "EspHostedCmdScanResult",
  "",
  sizeof(EspHostedCmdScanResult),
  0,
  esp_hosted_cmd_scan_result__field_descriptors,
  esp_hosted_cmd_scan_result__field_indices_by_name,
  0,  esp_hosted_cmd_scan_result__number_ranges,
  (ProtobufCMessageInit) esp_hosted_cmd_scan_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor esp_hosted_resp_scan_result__field_descriptors[2] =
{
  {
    "count",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(EspHostedRespScanResult, has_count),
    offsetof(EspHostedRespScanResult, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "entries",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedRespScanResult, n_entries),
    offsetof(EspHostedRespScanResult, entries),
    &esp_hosted_scan_result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned esp_hosted_resp_scan_result__field_indices_by_name[] = {
  0,   /* field[0] = count */
  1,   /* field[1] = entries */
};
static const ProtobufCIntRange esp_hosted_resp_scan_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor esp_hosted_resp_scan_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EspHostedRespScanResult",
  "EspHostedRespScanResult",
  "EspHostedRespScanResult",
  "",
  sizeof(EspHostedRespScanResult),
  2,
  esp_hosted_resp_scan_result__field_descriptors,
  esp_hosted_resp_scan_result__field_indices_by_name,
  1,  esp_hosted_resp_scan_result__number_ranges,
  (ProtobufCMessageInit) esp_hosted_resp_scan_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor esp_hosted_connected_stalist__field_descriptors[2] =
{
  {
    "mac",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(EspHostedConnectedSTAList, has_mac),
    offsetof(EspHostedConnectedSTAList, mac),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rssi",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(EspHostedConnectedSTAList, has_rssi),
    offsetof(EspHostedConnectedSTAList, rssi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned esp_hosted_connected_stalist__field_indices_by_name[] = {
  0,   /* field[0] = mac */
  1,   /* field[1] = rssi */
};
static const ProtobufCIntRange esp_hosted_connected_stalist__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor esp_hosted_connected_stalist__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EspHostedConnectedSTAList",
  "EspHostedConnectedSTAList",
  "EspHostedConnectedSTAList",
  "",
  sizeof(EspHostedConnectedSTAList),
  2,
  esp_hosted_connected_stalist__field_descriptors,
  esp_hosted_connected_stalist__field_indices_by_name,
  1,  esp_hosted_connected_stalist__number_ranges,
  (ProtobufCMessageInit) esp_hosted_connected_stalist__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define esp_hosted_cmd_connected_sta__field_descriptors NULL
#define esp_hosted_cmd_connected_sta__field_indices_by_name NULL
#define esp_hosted_cmd_connected_sta__number_ranges NULL
const ProtobufCMessageDescriptor esp_hosted_cmd_connected_sta__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EspHostedCmdConnectedSTA",
  "EspHostedCmdConnectedSTA",
  "EspHostedCmdConnectedSTA",
  "",
  sizeof(EspHostedCmdConnectedSTA),
  0,
  esp_hosted_cmd_connected_sta__field_descriptors,
  esp_hosted_cmd_connected_sta__field_indices_by_name,
  0,  esp_hosted_cmd_connected_sta__number_ranges,
  (ProtobufCMessageInit) esp_hosted_cmd_connected_sta__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor esp_hosted_resp_connected_sta__field_descriptors[2] =
{
  {
    "num",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(EspHostedRespConnectedSTA, has_num),
    offsetof(EspHostedRespConnectedSTA, num),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stations",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedRespConnectedSTA, n_stations),
    offsetof(EspHostedRespConnectedSTA, stations),
    &esp_hosted_connected_stalist__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned esp_hosted_resp_connected_sta__field_indices_by_name[] = {
  0,   /* field[0] = num */
  1,   /* field[1] = stations */
};
static const ProtobufCIntRange esp_hosted_resp_connected_sta__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor esp_hosted_resp_connected_sta__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EspHostedRespConnectedSTA",
  "EspHostedRespConnectedSTA",
  "EspHostedRespConnectedSTA",
  "",
  sizeof(EspHostedRespConnectedSTA),
  2,
  esp_hosted_resp_connected_sta__field_descriptors,
  esp_hosted_resp_connected_sta__field_indices_by_name,
  1,  esp_hosted_resp_connected_sta__number_ranges,
  (ProtobufCMessageInit) esp_hosted_resp_connected_sta__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor esp_hosted_cmd_set_power_save_mode__field_descriptors[1] =
{
  {
    "power_save_mode",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(EspHostedCmdSetPowerSaveMode, has_power_save_mode),
    offsetof(EspHostedCmdSetPowerSaveMode, power_save_mode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned esp_hosted_cmd_set_power_save_mode__field_indices_by_name[] = {
  0,   /* field[0] = power_save_mode */
};
static const ProtobufCIntRange esp_hosted_cmd_set_power_save_mode__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor esp_hosted_cmd_set_power_save_mode__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EspHostedCmdSetPowerSaveMode",
  "EspHostedCmdSetPowerSaveMode",
  "EspHostedCmdSetPowerSaveMode",
  "",
  sizeof(EspHostedCmdSetPowerSaveMode),
  1,
  esp_hosted_cmd_set_power_save_mode__field_descriptors,
  esp_hosted_cmd_set_power_save_mode__field_indices_by_name,
  1,  esp_hosted_cmd_set_power_save_mode__number_ranges,
  (ProtobufCMessageInit) esp_hosted_cmd_set_power_save_mode__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor esp_hosted_resp_set_power_save_mode__field_descriptors[1] =
{
  {
    "resp",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(EspHostedRespSetPowerSaveMode, has_resp),
    offsetof(EspHostedRespSetPowerSaveMode, resp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned esp_hosted_resp_set_power_save_mode__field_indices_by_name[] = {
  0,   /* field[0] = resp */
};
static const ProtobufCIntRange esp_hosted_resp_set_power_save_mode__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor esp_hosted_resp_set_power_save_mode__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EspHostedRespSetPowerSaveMode",
  "EspHostedRespSetPowerSaveMode",
  "EspHostedRespSetPowerSaveMode",
  "",
  sizeof(EspHostedRespSetPowerSaveMode),
  1,
  esp_hosted_resp_set_power_save_mode__field_descriptors,
  esp_hosted_resp_set_power_save_mode__field_indices_by_name,
  1,  esp_hosted_resp_set_power_save_mode__number_ranges,
  (ProtobufCMessageInit) esp_hosted_resp_set_power_save_mode__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define esp_hosted_cmd_get_power_save_mode__field_descriptors NULL
#define esp_hosted_cmd_get_power_save_mode__field_indices_by_name NULL
#define esp_hosted_cmd_get_power_save_mode__number_ranges NULL
const ProtobufCMessageDescriptor esp_hosted_cmd_get_power_save_mode__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EspHostedCmdGetPowerSaveMode",
  "EspHostedCmdGetPowerSaveMode",
  "EspHostedCmdGetPowerSaveMode",
  "",
  sizeof(EspHostedCmdGetPowerSaveMode),
  0,
  esp_hosted_cmd_get_power_save_mode__field_descriptors,
  esp_hosted_cmd_get_power_save_mode__field_indices_by_name,
  0,  esp_hosted_cmd_get_power_save_mode__number_ranges,
  (ProtobufCMessageInit) esp_hosted_cmd_get_power_save_mode__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor esp_hosted_resp_get_power_save_mode__field_descriptors[2] =
{
  {
    "power_save_mode",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(EspHostedRespGetPowerSaveMode, has_power_save_mode),
    offsetof(EspHostedRespGetPowerSaveMode, power_save_mode),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resp",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(EspHostedRespGetPowerSaveMode, has_resp),
    offsetof(EspHostedRespGetPowerSaveMode, resp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned esp_hosted_resp_get_power_save_mode__field_indices_by_name[] = {
  0,   /* field[0] = power_save_mode */
  1,   /* field[1] = resp */
};
static const ProtobufCIntRange esp_hosted_resp_get_power_save_mode__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor esp_hosted_resp_get_power_save_mode__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EspHostedRespGetPowerSaveMode",
  "EspHostedRespGetPowerSaveMode",
  "EspHostedRespGetPowerSaveMode",
  "",
  sizeof(EspHostedRespGetPowerSaveMode),
  2,
  esp_hosted_resp_get_power_save_mode__field_descriptors,
  esp_hosted_resp_get_power_save_mode__field_indices_by_name,
  1,  esp_hosted_resp_get_power_save_mode__number_ranges,
  (ProtobufCMessageInit) esp_hosted_resp_get_power_save_mode__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor esp_hosted_config_payload__field_descriptors[27] =
{
  {
    "msg",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(EspHostedConfigPayload, has_msg),
    offsetof(EspHostedConfigPayload, msg),
    &esp_hosted_config_msg_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd_get_mac_address",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, cmd_get_mac_address),
    &esp_hosted_cmd_get_status__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resp_get_mac_address",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, resp_get_mac_address),
    &esp_hosted_resp_get_status__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd_get_wifi_mode",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, cmd_get_wifi_mode),
    &esp_hosted_cmd_get_status__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resp_get_wifi_mode",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, resp_get_wifi_mode),
    &esp_hosted_resp_get_status__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd_set_wifi_mode",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, cmd_set_wifi_mode),
    &esp_hosted_cmd_get_status__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resp_set_wifi_mode",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, resp_set_wifi_mode),
    &esp_hosted_resp_get_status__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd_get_ap_config",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, cmd_get_ap_config),
    &esp_hosted_cmd_config__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resp_get_ap_config",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, resp_get_ap_config),
    &esp_hosted_resp_config__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd_set_ap_config",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, cmd_set_ap_config),
    &esp_hosted_cmd_config__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resp_set_ap_config",
    19,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, resp_set_ap_config),
    &esp_hosted_resp_config__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd_get_softap_config",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, cmd_get_softap_config),
    &esp_hosted_cmd_config__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resp_get_softap_config",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, resp_get_softap_config),
    &esp_hosted_resp_config__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd_set_softap_config",
    22,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, cmd_set_softap_config),
    &esp_hosted_cmd_config__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resp_set_softap_config",
    23,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, resp_set_softap_config),
    &esp_hosted_resp_config__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd_disconnect_ap",
    24,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, cmd_disconnect_ap),
    &esp_hosted_cmd_get_status__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resp_disconnect_ap",
    25,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, resp_disconnect_ap),
    &esp_hosted_resp_get_status__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd_scan_ap_list",
    26,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, cmd_scan_ap_list),
    &esp_hosted_cmd_scan_result__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resp_scan_ap_list",
    27,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, resp_scan_ap_list),
    &esp_hosted_resp_scan_result__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd_connected_stas_list",
    28,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, cmd_connected_stas_list),
    &esp_hosted_cmd_connected_sta__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resp_connected_stas_list",
    29,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, resp_connected_stas_list),
    &esp_hosted_resp_connected_sta__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd_set_mac_address",
    30,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, cmd_set_mac_address),
    &esp_hosted_cmd_set_mac_address__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resp_set_mac_address",
    31,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, resp_set_mac_address),
    &esp_hosted_resp_set_mac_address__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd_set_power_save_mode",
    32,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, cmd_set_power_save_mode),
    &esp_hosted_cmd_set_power_save_mode__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resp_set_power_save_mode",
    33,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, resp_set_power_save_mode),
    &esp_hosted_resp_set_power_save_mode__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd_get_power_save_mode",
    34,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, cmd_get_power_save_mode),
    &esp_hosted_cmd_get_power_save_mode__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resp_get_power_save_mode",
    35,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EspHostedConfigPayload, payload_case),
    offsetof(EspHostedConfigPayload, resp_get_power_save_mode),
    &esp_hosted_resp_get_power_save_mode__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned esp_hosted_config_payload__field_indices_by_name[] = {
  19,   /* field[19] = cmd_connected_stas_list */
  15,   /* field[15] = cmd_disconnect_ap */
  7,   /* field[7] = cmd_get_ap_config */
  1,   /* field[1] = cmd_get_mac_address */
  25,   /* field[25] = cmd_get_power_save_mode */
  11,   /* field[11] = cmd_get_softap_config */
  3,   /* field[3] = cmd_get_wifi_mode */
  17,   /* field[17] = cmd_scan_ap_list */
  9,   /* field[9] = cmd_set_ap_config */
  21,   /* field[21] = cmd_set_mac_address */
  23,   /* field[23] = cmd_set_power_save_mode */
  13,   /* field[13] = cmd_set_softap_config */
  5,   /* field[5] = cmd_set_wifi_mode */
  0,   /* field[0] = msg */
  20,   /* field[20] = resp_connected_stas_list */
  16,   /* field[16] = resp_disconnect_ap */
  8,   /* field[8] = resp_get_ap_config */
  2,   /* field[2] = resp_get_mac_address */
  26,   /* field[26] = resp_get_power_save_mode */
  12,   /* field[12] = resp_get_softap_config */
  4,   /* field[4] = resp_get_wifi_mode */
  18,   /* field[18] = resp_scan_ap_list */
  10,   /* field[10] = resp_set_ap_config */
  22,   /* field[22] = resp_set_mac_address */
  24,   /* field[24] = resp_set_power_save_mode */
  14,   /* field[14] = resp_set_softap_config */
  6,   /* field[6] = resp_set_wifi_mode */
};
static const ProtobufCIntRange esp_hosted_config_payload__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 10, 1 },
  { 0, 27 }
};
const ProtobufCMessageDescriptor esp_hosted_config_payload__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EspHostedConfigPayload",
  "EspHostedConfigPayload",
  "EspHostedConfigPayload",
  "",
  sizeof(EspHostedConfigPayload),
  27,
  esp_hosted_config_payload__field_descriptors,
  esp_hosted_config_payload__field_indices_by_name,
  2,  esp_hosted_config_payload__number_ranges,
  (ProtobufCMessageInit) esp_hosted_config_payload__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue esp_hosted_encryption_mode__enum_values_by_number[8] =
{
  { "Type_Open", "ESP_HOSTED_ENCRYPTION_MODE__Type_Open", 0 },
  { "Type_WEP", "ESP_HOSTED_ENCRYPTION_MODE__Type_WEP", 1 },
  { "Type_WPA_PSK", "ESP_HOSTED_ENCRYPTION_MODE__Type_WPA_PSK", 2 },
  { "Type_WPA2_PSK", "ESP_HOSTED_ENCRYPTION_MODE__Type_WPA2_PSK", 3 },
  { "Type_WPA_WPA2_PSK", "ESP_HOSTED_ENCRYPTION_MODE__Type_WPA_WPA2_PSK", 4 },
  { "Type_WPA2_ENTERPRISE", "ESP_HOSTED_ENCRYPTION_MODE__Type_WPA2_ENTERPRISE", 5 },
  { "Type_WPA3_PSK", "ESP_HOSTED_ENCRYPTION_MODE__Type_WPA3_PSK", 6 },
  { "Type_WPA2_WPA3_PSK", "ESP_HOSTED_ENCRYPTION_MODE__Type_WPA2_WPA3_PSK", 7 },
};
static const ProtobufCIntRange esp_hosted_encryption_mode__value_ranges[] = {
{0, 0},{0, 8}
};
static const ProtobufCEnumValueIndex esp_hosted_encryption_mode__enum_values_by_name[8] =
{
  { "Type_Open", 0 },
  { "Type_WEP", 1 },
  { "Type_WPA2_ENTERPRISE", 5 },
  { "Type_WPA2_PSK", 3 },
  { "Type_WPA2_WPA3_PSK", 7 },
  { "Type_WPA3_PSK", 6 },
  { "Type_WPA_PSK", 2 },
  { "Type_WPA_WPA2_PSK", 4 },
};
const ProtobufCEnumDescriptor esp_hosted_encryption_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EspHostedEncryptionMode",
  "EspHostedEncryptionMode",
  "EspHostedEncryptionMode",
  "",
  8,
  esp_hosted_encryption_mode__enum_values_by_number,
  8,
  esp_hosted_encryption_mode__enum_values_by_name,
  1,
  esp_hosted_encryption_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue esp_hosted_config_msg_type__enum_values_by_number[26] =
{
  { "TypeCmdGetMACAddress", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeCmdGetMACAddress", 0 },
  { "TypeRespGetMACAddress", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeRespGetMACAddress", 1 },
  { "TypeCmdGetWiFiMode", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeCmdGetWiFiMode", 2 },
  { "TypeRespGetWiFiMode", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeRespGetWiFiMode", 3 },
  { "TypeCmdSetWiFiMode", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeCmdSetWiFiMode", 4 },
  { "TypeRespSetWiFiMode", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeRespSetWiFiMode", 5 },
  { "TypeCmdGetAPConfig", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeCmdGetAPConfig", 6 },
  { "TypeRespGetAPConfig", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeRespGetAPConfig", 7 },
  { "TypeCmdSetAPConfig", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeCmdSetAPConfig", 8 },
  { "TypeRespSetAPConfig", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeRespSetAPConfig", 9 },
  { "TypeCmdGetSoftAPConfig", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeCmdGetSoftAPConfig", 10 },
  { "TypeRespGetSoftAPConfig", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeRespGetSoftAPConfig", 11 },
  { "TypeCmdSetSoftAPConfig", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeCmdSetSoftAPConfig", 12 },
  { "TypeRespSetSoftAPConfig", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeRespSetSoftAPConfig", 13 },
  { "TypeCmdDisconnectAP", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeCmdDisconnectAP", 14 },
  { "TypeRespDisconnectAP", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeRespDisconnectAP", 15 },
  { "TypeCmdGetAPScanList", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeCmdGetAPScanList", 16 },
  { "TypeRespGetAPScanList", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeRespGetAPScanList", 17 },
  { "TypeCmdGetConnectedSTAList", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeCmdGetConnectedSTAList", 18 },
  { "TypeRespGetConnectedSTAList", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeRespGetConnectedSTAList", 19 },
  { "TypeCmdSetMacAddress", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeCmdSetMacAddress", 20 },
  { "TypeRespSetMacAddress", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeRespSetMacAddress", 21 },
  { "TypeCmdSetPowerSaveMode", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeCmdSetPowerSaveMode", 22 },
  { "TypeRespSetPowerSaveMode", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeRespSetPowerSaveMode", 23 },
  { "TypeCmdGetPowerSaveMode", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeCmdGetPowerSaveMode", 24 },
  { "TypeRespGetPowerSaveMode", "ESP_HOSTED_CONFIG_MSG_TYPE__TypeRespGetPowerSaveMode", 25 },
};
static const ProtobufCIntRange esp_hosted_config_msg_type__value_ranges[] = {
{0, 0},{0, 26}
};
static const ProtobufCEnumValueIndex esp_hosted_config_msg_type__enum_values_by_name[26] =
{
  { "TypeCmdDisconnectAP", 14 },
  { "TypeCmdGetAPConfig", 6 },
  { "TypeCmdGetAPScanList", 16 },
  { "TypeCmdGetConnectedSTAList", 18 },
  { "TypeCmdGetMACAddress", 0 },
  { "TypeCmdGetPowerSaveMode", 24 },
  { "TypeCmdGetSoftAPConfig", 10 },
  { "TypeCmdGetWiFiMode", 2 },
  { "TypeCmdSetAPConfig", 8 },
  { "TypeCmdSetMacAddress", 20 },
  { "TypeCmdSetPowerSaveMode", 22 },
  { "TypeCmdSetSoftAPConfig", 12 },
  { "TypeCmdSetWiFiMode", 4 },
  { "TypeRespDisconnectAP", 15 },
  { "TypeRespGetAPConfig", 7 },
  { "TypeRespGetAPScanList", 17 },
  { "TypeRespGetConnectedSTAList", 19 },
  { "TypeRespGetMACAddress", 1 },
  { "TypeRespGetPowerSaveMode", 25 },
  { "TypeRespGetSoftAPConfig", 11 },
  { "TypeRespGetWiFiMode", 3 },
  { "TypeRespSetAPConfig", 9 },
  { "TypeRespSetMacAddress", 21 },
  { "TypeRespSetPowerSaveMode", 23 },
  { "TypeRespSetSoftAPConfig", 13 },
  { "TypeRespSetWiFiMode", 5 },
};
const ProtobufCEnumDescriptor esp_hosted_config_msg_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "EspHostedConfigMsgType",
  "EspHostedConfigMsgType",
  "EspHostedConfigMsgType",
  "",
  26,
  esp_hosted_config_msg_type__enum_values_by_number,
  26,
  esp_hosted_config_msg_type__enum_values_by_name,
  1,
  esp_hosted_config_msg_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
