#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := network_adapter
EXTRA_LDFLAGS += -lesp32_at_core
EXTRA_COMPONENT_DIRS := $(realpath ../../common)
include $(IDF_PATH)/make/project.mk

