#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := sdio_slave
EXTRA_LDFLAGS += -lesp32_at_core
include $(IDF_PATH)/make/project.mk

