// Mock per-side artefacts. The backend will later supply the real generated
// `sdkconfig` plus the set of keys that came from sdkconfig.defaults[.<chip>].
// Tiers: base (non-hosted) · hosted (CONFIG_ESP_HOSTED*) · from-defaults.

export const LOG_PATHS = {
  host: '~/.esplab/runs/latest/host.log',
  cp: '~/.esplab/runs/latest/cp.log',
}
export const SDKCONFIG_PATHS = {
  host: 'examples/system/hosted_events/mcu_host/sdkconfig',
  cp: 'examples/system/hosted_events/cp/sdkconfig',
}

// full generated sdkconfig (excerpt)
export const HOST_SDKCONFIG = `# Host (esp32p4) — generated sdkconfig (excerpt)
CONFIG_IDF_TARGET="esp32p4"
CONFIG_IDF_TARGET_ESP32P4=y
CONFIG_BOOTLOADER_LOG_LEVEL_INFO=y
CONFIG_PARTITION_TABLE_SINGLE_APP=y
CONFIG_FREERTOS_HZ=1000
CONFIG_ESP_MAIN_TASK_STACK_SIZE=3584
CONFIG_ESP_HOSTED=y
CONFIG_ESP_HOSTED_HOST_FEAT_RPC=y
CONFIG_ESP_HOSTED_HOST_FEAT_RPC_EXT_V2=y
CONFIG_ESP_HOSTED_HOST_FEAT_WIFI=y
CONFIG_ESP_HOSTED_HOST_FEAT_HEARTBEAT=y
CONFIG_ESP_HOSTED_HOST_TRANSPORT_BUS_SDIO=y
CONFIG_ESP_HOSTED_HOST_TRANSPORT_RESTART_ON_FAILURE=n
CONFIG_ESP_HOSTED_SDIO_RX_INTR_WAIT_FOREVER=y
CONFIG_ESP_HOSTED_SDIO_HOST_STREAMING_MODE=y
CONFIG_EXAMPLE_HEARTBEAT_INTERVAL_SEC=5
CONFIG_EXAMPLE_HEARTBEAT_TIMEOUT_SEC=6
CONFIG_LWIP_IPV6=y
CONFIG_LWIP_MAX_SOCKETS=10
CONFIG_LOG_DEFAULT_LEVEL_INFO=y
`
// keys explicitly set by sdkconfig.defaults / sdkconfig.defaults.esp32p4
export const HOST_DEFAULTS = [
  'CONFIG_ESP_HOSTED', 'CONFIG_ESP_HOSTED_HOST_FEAT_RPC', 'CONFIG_ESP_HOSTED_HOST_FEAT_RPC_EXT_V2',
  'CONFIG_ESP_HOSTED_HOST_FEAT_WIFI', 'CONFIG_ESP_HOSTED_HOST_FEAT_HEARTBEAT',
  'CONFIG_ESP_HOSTED_HOST_TRANSPORT_RESTART_ON_FAILURE',
  'CONFIG_EXAMPLE_HEARTBEAT_INTERVAL_SEC', 'CONFIG_EXAMPLE_HEARTBEAT_TIMEOUT_SEC',
]

export const CP_SDKCONFIG = `# Co-processor (esp32c5) — generated sdkconfig (excerpt)
CONFIG_IDF_TARGET="esp32c5"
CONFIG_IDF_TARGET_ESP32C5=y
CONFIG_PARTITION_TABLE_TWO_OTA=y
CONFIG_ESP_HOSTED_CP=y
CONFIG_ESP_HOSTED_CP_FEAT_RPC_EXT_V2=y
CONFIG_ESP_HOSTED_CP_FEAT_WIFI=y
CONFIG_ESP_HOSTED_CP_TRANSPORT_BUS_SDIO=y
CONFIG_ESP_HOSTED_SDIO_SLAVE_SEND_STREAM=y
CONFIG_ESP_WIFI_STATIC_RX_BUFFER_NUM=10
CONFIG_ESP_WIFI_DYNAMIC_RX_BUFFER_NUM=32
CONFIG_BT_ENABLED=y
CONFIG_BT_NIMBLE_ENABLED=y
CONFIG_LOG_DEFAULT_LEVEL_INFO=y
`
export const CP_DEFAULTS = [
  'CONFIG_ESP_HOSTED_CP', 'CONFIG_ESP_HOSTED_CP_FEAT_RPC_EXT_V2', 'CONFIG_ESP_HOSTED_CP_FEAT_WIFI',
  'CONFIG_ESP_HOSTED_CP_TRANSPORT_BUS_SDIO', 'CONFIG_BT_ENABLED',
]
